name: CI

on:
  push:
    branches: ["**"]
  schedule:
    - cron: "0 4 * * 3" # Every Wednesday at 4:00 UTC

permissions:
  contents: read # For actions/checkout@v4

jobs:
  unit-tests:
    name: PHPUnit tests on ubuntu-latest
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo_mysql
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run coverage report
        run: ./vendor/bin/phpunit --testsuite="unit" --coverage-text="coverage_text.txt" --coverage-html="coverage_html"

      - name: Send coverage text to step summary
        run: cat coverage_text.txt >> $GITHUB_STEP_SUMMARY

      - name: Create archive for coverage html
        run: tar -czvf coverage_html.tar.gz coverage_html

      - name: Upload coverage html archive
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          overwrite: true
          path: ./coverage_html.tar.gz

  EndToEnd:
    needs: unit-tests
    name: EndToEnd tests on ubuntu-latest
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo_mysql
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Change permissions
        run: |
          chmod +x ./tests/EndToEnd/mariadb_install.sh
          chmod +x ./tests/EndToEnd/mariadb_create_database_with_user.sh
          chmod +x ./tests/EndToEnd/EndToEnd.sql

      - name: Install MariaDB and create database with user
        run: ./tests/EndToEnd/mariadb_install.sh projom EndToEnd

      - name: Creating database tables with mock data
        run: mysql --user=projom --password=projom < ./tests/EndToEnd/EndToEnd.sql

      - name: Run test suite
        run: ./vendor/bin/phpunit --testsuite="EndToEnd"

  psalm-security-scan:
    name: Psalm static security analysis on ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      security-events: write # For github/codeql-action/upload-sarif to upload results

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Psalm security scan
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          security_analysis: true
          show_info: true
          report_file: results.sarif
        continue-on-error: true

      - name: Upload security analysis results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
