name: CI

on: [push]

permissions:
  contents: write

jobs:
  static-analysis:
    name: Static analysis on php ${{ matrix.php_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.2"]
        os: [ubuntu-latest]

    steps:  
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer, psalm

      - name: Install dependencies
        run: composer install --no-dev

      - name: Run psalm static analysis
        run: psalm --report="static_results.sarif" --no-progress --no-cache >> /dev/null

      - name: Run psalm taint analysis
        run: psalm --report="taint_results.sarif" --no-progress --no-cache >> /dev/null

      - name: Upload static analysis results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: static_results.sarif
          category: Psalm static analysis

      - name: Upload taint analysis results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: taint_results.sarif
          category: Psalm taint analysis

  unit-tests:
    name: Test on php ${{ matrix.php_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.2"]
        os: [ubuntu-latest]

    steps:  
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo_mysql
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run coverage report
        run: ./vendor/bin/phpunit --coverage-text="phpunit_coverage.txt"

      - name: Coverage summary
        run: cat phpunit_coverage.txt >> $GITHUB_STEP_SUMMARY