name: CI

on:
  push:
    branches: ["**"]
  schedule:
    - cron: "0 4 * * 3" # Every Wednesday at 4:00 UTC

jobs:
  unit-tests:
    name: Unit tests on ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run unit test coverage reports
        run: ./vendor/bin/phpunit --testsuite="Unit"

      - name: Send text coverage report to step summary
        run: cat coverage.txt >> $GITHUB_STEP_SUMMARY

      - name: Create archive for html coverage
        run: tar -czvf html-coverage.tar.gz html-coverage

      - name: Upload coverage html archive
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage
          overwrite: true
          path: ./html-coverage.tar.gz

      - name: Create coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: ./clover-coverage.xml
          coverage_badge_path: phpunit-coverage-badge.svg
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          commit_name: github-actions[bot]
          commit_email: github-actions[bot]@users.noreply.github.com

  integration-tests:
    name: Integration tests on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, pdo_sqlite
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run integration test suite
        run: ./vendor/bin/phpunit --testsuite="Integration"

  code-security-analysis:
    name: Psalm taint analysis on ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Psalm taint analysis scan
        run: ./vendor/bin/psalm --taint-analysis --output-format=sarif > taint-results.sarif

      - name: Upload security analysis results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: taint-results.sarif
          category: psalm-taint-analysis

  code-static-analysis:
    name: Psalm static analysis on ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Psalm annotation and report
        continue-on-error: true
        run: ./vendor/bin/psalm --output-format=github --report=ql-results.sarif

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ql-results.sarif
          category: psalm-static-analysis
