name: Psalm Security Scan

on:
  push:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '0 4 * * 3'

permissions:
  contents: read

jobs:
  psalm-security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For actions/checkout to fetch code
      security-events: write # For github/codeql-action/upload-sarif to upload results

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Psalm security scan
        uses: psalm/psalm-github-security-scan@f3e6fd9432bc3e44aec078572677ce9d2ef9c287

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
